### ISSUE TITLE
Validation Set

### ISSUE THREAD

**Issue by YanhuiS** [LiYi199983/FDBTrack#1]

**Comment by LiYi199983** [comment]
感谢您的提醒，我们也注意到了这个错误，这是我们在这个领域的第一篇论文，请多包含。我们将为这个库添加一个代码，用以删除视频前一半的结果。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiYi199983/FDBTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上8:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiYi199983/FDBTrack] Validation Set (Issue #1)





 
我刚跑了你的代码，发现你的结果是整个训练集的结果，而不是验证集的结果。

**Comment by LiYi199983** [comment]
请在运行完主程序后，对结果执行这条代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiYi199983/FDBTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上8:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiYi199983/FDBTrack] Validation Set (Issue #1)





 
我刚跑了你的代码，发现你的结果是整个训练集的结果，而不是验证集的结果。

**Comment by YanhuiS** [comment]
谢谢谢谢，方便的话可以加一下我的微信吗？我有点问题想跟您讨论一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月22日 20:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [LiYi199983/FDBTrack] Validation Set (Issue #1) |

请在运行完主程序后，对结果执行这条代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiYi199983/FDBTrack" ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上8:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiYi199983/FDBTrack] Validation Set (Issue #1)






我刚跑了你的代码，发现你的结果是整个训练集的结果，而不是验证集的结果。

**Comment by LiYi199983** [comment]
那个是我导师的邮箱，你用第二作者的邮箱找我就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiYi199983/FDBTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiYi199983/FDBTrack] Validation Set (Issue #1)





 我给你的另一个投稿邮箱发邮件了
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2023年03月22日 20:20 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;、State ***@***.***&gt; |
 | 主题 | Re: [LiYi199983/FDBTrack] Validation Set (Issue #1) |
 
 点击链接加入群聊【目标跟踪交流群】：https://jq.qq.com/?_wv=1027&amp;amp;k=GPRlSS4l
 你可以加这个qq群，我是里面的管理，进去可以直接私聊我
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "LiYi199983/FDBTrack" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2023年3月22日(星期三) 晚上8:12
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [LiYi199983/FDBTrack] Validation Set (Issue #1)
 
 
 
 
 
 
 谢谢谢谢，方便的话可以加一下我的微信吗？我有点问题想跟您讨论一下
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 日期 | 2023年03月22日 20:11 |
 | 收件人 | ***@***.***&amp;gt; |
 | 抄送至 | ***@***.***&amp;gt;、State ***@***.***&amp;gt; |
 | 主题 | Re: [LiYi199983/FDBTrack] Validation Set (Issue #1) |
 
 请在运行完主程序后，对结果执行这条代码
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人: "LiYi199983/FDBTrack" ***@***.***&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2023年3月22日(星期三) 晚上8:01
 ***@***.***&amp;amp;gt;;
 ***@***.***&amp;amp;gt;;
 主题:&amp;amp;nbsp;[LiYi199983/FDBTrack] Validation Set (Issue #1)
 
 
 
 
 
 
 我刚跑了你的代码，发现你的结果是整个训练集的结果，而不是验证集的结果。

**Comment by YanhuiS** [comment]
执行啥代码呀？我这没看到

**Comment by YanhuiS** [comment]
没加错吧？我没收到

**Comment by LiYi199983** [comment]
你是山东潍坊的吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiYi199983/FDBTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiYi199983/FDBTrack] Validation Set (Issue #1)





 
没加错吧？我没收到
